default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: example_development

test:
  <<: *default
  database: example_test

production:
  primary: &primary_production
    <<: *default
    database: example_production
    username: example
    password: <%= ENV["EXAMPLE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: example_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: example_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: example_production_cable
    migrations_paths: db/cable_migrate
